import React, { useState } from "react";
import "./PasteResume.css";
import axios from "axios";

const PasteResume = () => {
  const [resumeText, setResumeText] = useState(""); //it will update the text that is pasted by the user in the textarea
  const [result, setResult] = useState(null); //result generated by AI
  const [loading, setLoading] = useState(false);

  const handleAnalyze = async () => {
    if (!resumeText.trim()) return alert("Please paste your resume first!");

    setLoading(true);

    try {
      const response = await axios.post("http://localhost:5000/analyze", {
        resume: resumeText,
      });
      const raw = response.data.feedback;
      const cleaned = raw.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(cleaned);
      setResult(parsed);
    } catch (error) {
      console.error("Error: ", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="pasteResume">
      <div className="paste-div">
        <h3>Paste Resume</h3>
        <textarea
          placeholder="Paste your resume here"
          value={resumeText}
          onChange={(e) => setResumeText(e.target.value)}
        />
        <button onClick={handleAnalyze}>
          {loading ? "Analyzing..." : "Analyze My Resume"}
        </button>
        {result && (
          <div className="results">
            <h2>Score: {result.score}/10</h2>
            <div className="result-card">
              <h3>✅ Strengths</h3>
              {result.strengths.map((s, i) => (
                <p key={i}>{s}</p>
              ))}
            </div>
            <div className="result-card">
              <h3>❌ Weaknesses</h3>
              {result.weaknesses.map((w, i) => (
                <p key={i}>{w}</p>
              ))}
            </div>
            <div className="result-card">
              <h3>💡 Suggestions</h3>
              {result.suggestions.map((s, i) => (
                <p key={i}>{s}</p>
              ))}
            </div>
            <div className="result-card">
              <h3>🎯 ATS Tips</h3>
              {result.ats_tips.map((a, i) => (
                <p key={i}>{a}</p>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PasteResume;
